<?php


	echo "<html>
			<head>
	  			<title>PoliClínica FAP Betim\MG By CMN®</title>
	  			<meta charset='utf-8'>
	  			<link rel ='shortcut icon' href = 'image/logo.ico'>
	  			<link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' 
	  				integrity='sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T' crossorigin='anonymous'>
	  			<link rel='stylesheet' type='text/css' href='css/global.css'>
			
				
			</head>
			<body>
				<br><br>
				<img src='image/heard.png'>
				<hr>
				<p><h4>FACULDADE PITÁGORAS - UNIDADE BETIM <br> PoliClínica Ondontologica
				<hr>
				Ordem de Serviço Nº: 1.004
				<br>
				Nome do Paciente: CRISTIANO MARTINS NUNES
				<br>
				Data/Hora O.S: 2014-01-01 12:00:11  
				<br>
				<hr>
				<center><h3>Orçamento - Lista de Serviço(s)<h3></center>

			</body>";



?>

